### ISSUE TITLE
pinning support

### ISSUE THREAD

**Issue by abma** [spring/pr-downloader#12]
to make it the ultimate download tool, pinning support is required:

cat ~/.spring/rapid/main.cfg 
[tags]
pinned = ea:latest,ba:latest,...

**Comment by gajop** [comment]
It's been a while since this was updated, but I think it would be really useful.
Pinning as well as upgrading (--upgrade) really made auto-updating much easier when Python rapid was used: https://github.com/tvo/rapid#usage.
Any guestimate how much time it would require to do this?

**Comment by abma** [comment]
intuitively i would think 6 hours, so 12 hours. :)

**Comment by gajop** [comment]
I suggest we just forget about this.

**Comment by abma** [comment]
haveing all features of "rapid" isn't needed any more it seems as pr-downloader mostly is used via api and not cli.

**Comment by gajop** [comment]
Oh, it's still used through the CLI. I'm working on a game-agnostic launcher (https://github.com/Spring-Chobby/ChobbyLauncher/) and it uses pr-downloader's CLI to download stuff.

This is why I need a (CLI) way to confirm whether things have been downloaded - otherwise the launcher won't know if all resources are present to run the lobby

**Comment by abma** [comment]
oh, ok, good to know

**Comment by ashdnazg** [comment]
did you consider using ctypes and hook directly into a shared library?

**Comment by gajop** [comment]
@ashdnazg That's probably not a bad idea, although I would still like to use the pr-downloader API, rather than the Spring one. I don't think there would be a (huge) benefit from using it right now.
