### ISSUE TITLE
non-torrent/single file/engine download fails when file already exist but mismatches

### ISSUE THREAD

**Issue by abma** [spring/pr-downloader#56]
On linux downloading 94.1

cc@inspiron:~/.spring/weblobby/pr-downloader$ ./pr-downloader --filesystem-writepath ~/.spring/weblobby/ --download-engine 94.1
pr-downloader 0.7-51-gfd4b556
[Info] Using filesystem-writepath: /home/cc/.spring/weblobby/
[Error] ../../../../../tools/pr-downloader/src/pr-downloader.cpp:84:search(): engine dl
[Error] ../../../../../../tools/pr-downloader/src/FileSystem/File.cpp:80:Open(): File already exists but file-size missmatched
[Info] opened /home/cc/.spring/weblobby//engine/spring_94.1_minimal-portable-linux64-static.7z
[Error] ../../../../../../../tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:202:verifyAndGetNextPiece(): md5 sum missmatch e0d3244e06a8fc0dc59d1d184c169c7c 03311b120e0922172f69c071968c7252

[Info] /home/cc/.spring/weblobby//engine/spring_94.1_minimal-portable-linux64-static.7z /home/cc/.spring/weblobby//engine/94.1
[Error] ../../../../../../tools/pr-downloader/src/FileSystem/SevenZipArchive.cpp:133:CSevenZipArchive(): Error opening /home/cc/.spring/weblobby//engine/spring_94.1_minimal-portable-linux64-static.7z: Unknown error
[Info] done
[Info] Download complete!

**Comment by MadrMan** [comment]
Would be nice if this could get fixed in some manner (by redownloading for example), as users who fail an engine download through SL currently are stuck in that state, until they manually delete the downloaded archive (something the average user will never do, and as such will never be able to play)

C:\Users\Ralph\Documents\My Games\Spring\engine\100.0>pr-downloader --download-engine 101.0
pr-downloader 0.7-176-gdfb39db
[Error] ../../tools/pr-downloader/src/pr-downloader.cpp:83:search(): engine dl
[Info] XmlRpcCurlClient new client: host api.springfiles.com, port 80.
[Info] XmlRpcCurlClient::execute: method springfiles.search.
[Info] XmlRpcCurlClient::execute: method springfiles.search completed.
[Info] Using filesystem-writepath: C:\Users\Ralph\Documents\My Games\Spring
[Info] opened C:\Users\Ralph\Documents\My Games\Spring\engine\spring_101.0_minimal-portable.7z
[Error] ../../tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:239:verifyAndGetNextPieces(): md5 sum missmatch 5534b790d5f2c1ae13d133ffc91bb82b e7b2fb5552c98075c81643002e827604
[Progress]   0% [                              ] 0/0
[Info] Extracting C:\Users\Ralph\Documents\My Games\Spring\engine\spring_101.0_minimal-portable.7z to C:\Users\Ralph\Documents\My Games\Spring\engine\101.0
[Error] ../../tools/pr-downloader/src/FileSystem/SevenZipArchive.cpp:138:CSevenZipArchive(): Error opening C:\Users\Ralph\Documents\My Games\Spring\engine\spring_101.0_minimal-portable.7z: Archive not found
[Info] done
[Info] Download complete!

**Comment by abma** [comment]
this issue was fixed some time ago, with current prdownloader version it should work.

current version is 0.7-322-g198364a
